version: '3'
services:
  postgresql:
    image: postgres:16.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend-app:
    build:
      context: .
      dockerfile: backend.Dockerfile
    depends_on:
      - postgresql
    ports:
      - "8080:8080"  
    volumes:
      - maven_cache:/root/.m2

  bank-card-app:
    build:
      context: .
      dockerfile: bankcard.Dockerfile
    depends_on:
      - postgresql
    ports:
      - "8081:8081"
    volumes:
      - maven_cache:/root/.m2
volumes:
  pgdata: { }
  maven_cache: { }