filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/logs/app.log
    multiline.pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
    multiline.negate: true
    multiline.match: after

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "backend-logs"

setup.kibana:
  host: "http://kibana:5601"

setup.template.name: "backend-logs"
setup.template.pattern: "backend-logs"