filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
    exclude_files: ['.gz$']

output.logstash:
  hosts: ["logstash:5044"]
