version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  postgres_data:
